sELECT CONVERT(DATE,DATE_) AS DATE2 ,* FROM SALES where CITY='ANKARA'
ORDER BY DATE_

SELECT *FROM SALES

UPDATE SALES SET DATE2=CONVERT(DATE,DATE_)

SELECT CITY ,DATE2,SUM(TOTALPRICE) AS TOTALPRICE 

FROM SALES WHERE CITY='ANKARA' GROUP BY CITY,DATE2

ORDER BY CITY,DATE2

 