--CREATE VIEW WVORDERS 
--AS
--SELECT * FROM ORDERS

--USER DEFINED FUNCTION

CREATE FUNCTION DBO.TOPLA(@SAYI1 AS INT,@SAYI2 AS INT)
RETURNS INT
AS 
BEGIN
	DECLARE @SONUC AS INT
	SET @SONUC=@SAYI1+@SAYI2
	RETURN @SONUC
END

SELECT DBO.TOPLA(15,10)




CREATE FUNCTION DBO.CALCULATE_AGE(@BIRTHDATE AS DATE)
RETURNS INT
AS 
BEGIN
DECLARE @RESULT AS INT 
SET @RESULT=DATEDIFF(YEAR,@BIRTHDATE,GETDATE())
RETURN RESULT