--DATETIME FUNCTÝONS()

--DATEADD()

DECLARE @TARIH AS DATETIME
SET @TARIH='2023-01-01 16:21:37'

DECLARE @TARIH2 AS DATETIME
SET @TARIH2=DATEADD(MONTH,6,@TARIH)

--SELECT @TARIH,@TARIH2

--SELECT DATEDIFF(MONTH,@TARIH,@TARIH2)
--SELECT DATEFROMPARTS(2023,8,21)
SELECT DATEPART(MONTH,@TARIH2)

SELECT GETDATE()




