DECLARE @I AS INT=0

--WHILE @I<10
--BEGIN
--PRINT @I
--SET @I+=1
--END
DECLARE @AD AS VARCHAR(50)
DECLARE @CINSIYET AS VARCHAR(50)
DECLARE @SOYAD AS VARCHAR(50)
DECLARE @DOGUMTARIHI AS DATE

WHILE @I<1
BEGIN
SELECT @AD=AD ,@CINSIYET=CINSIYET FROM ISIMLER WHERE ID=ROUND(RAND()*611,0)
SELECT @SOYAD=SOYAD  FROM SOYISIMLER WHERE ID=ROUND(RAND()*1000,0)
SET @DOGUMTARIHI=DATEADD(YEAR,ROUND(RAND()*18250,0)
INSERT INTO KISILER (AD,SOYAD,CINSIYET,DOGUMTARIHI) VALUES(
(@AD,@SOYAD,@CINSIYET,@DOGUMTARIHI)

SET @I+=1
END

