-- TSQL STRÝNG FUNCTÝONS--
--SUBSTÝNG() ,LOWER() ,UPPER()

DECLARE @KELIME AS VARCHAR(100) 
SET @KELIME='HELLO WORLD'

SELECT SUBSTRING(@KELIME,1,5) --HELLO--
SELECT SUBSTRING(@KELIME,1,7) --HELLO W--
SELECT LOWER(SUBSTRING(@KELIME,1,5)) --hello--
SELECT UPPER(LOWER(SUBSTRING(@KELIME,1,5))) --HELLO--

--RIGHT() ,LEFT()

DECLARE @KELIME1 AS VARCHAR(100) 
SET @KELIME1='HELLO WORLD1'

SELECT LEFT(@KELIME1,7) --HELLO W--
SELECT RIGHT(@KELIME1,7) --WORLD1 --


-- LTRIM(),RTRIM(),TRIM()

DECLARE @KELIME2 AS VARCHAR(100) 
SET @KELIME2='  HELLO WORLD2  '

SELECT LTRIM(@KELIME2)
SELECT RTRIM(@KELIME2)
SELECT TRIM(@KELIME2)

--REPLACE()

DECLARE @KELIME3 AS VARCHAR(100) 
SET @KELIME3='DOÐUKAN POLATEL'

SELECT REPLACE(@KELIME3,'Ð','G')
SELECT REPLACE(@KELIME3,'POLATEL','POLAT')

--LEN()

SELECT LEN(@KELIME3)


--STRING_SPLIT()

DECLARE @KELIME4 AS VARCHAR(100) 
SET @KELIME4='DOÐUKAN POLATEL'

SELECT *FROM string_split(@KELIME4,' ')










