--SELECT USERS.*,ADDRESS.ADRESS_TEXT 

---FROM USERS ,ADDRESS

---WHERE USERS.ID=ADDRESS.USERID AND USERS.ID=1


SELECT U.NAMESURNAME,U.EMAIL,U.EMAIL,A.ADRESS_TEXT

FROM USERS U
JOIN ADDRESS A ON U.ID=A.USERID


